location_homepage:
    path:     /location
    defaults: { _controller: "RentBundle:Location:index" }
    methods:  GET

location_show:
    path:    /showRent/{id}
    defaults: { _controller: "RentBundle:Location:show" }
    methods:  GET

location_new:
    path:     /newRent
    defaults: { _controller: "RentBundle:Location:new" }
    methods:  [GET, POST]

location_edit:
    path:    /editRent{id}
    defaults: { _controller: "RentBundle:Location:edit" }
    methods:  [GET, POST]

location_delete:
    path:    /deleteRent{id}
    defaults: { _controller: "RentBundle:Location:delete" }
    methods:  DELETE

location_search:
    path:    /rech
    defaults: { _controller: "RentBundle:Location:searchbytitle" }
    methods:  [POST]