esprit_api_homepage:
    path:     /
    defaults: { _controller: EspritApiBundle:Default:index }


allbb:
    path:     /posts/all
    defaults: { _controller: EspritApiBundle:Blog:allpost }




#find_post1:
 #   path:     /posts/recherchepost1/{recherche}
  #  defaults: { _controller: EspritApiBundle:Blog:findpost }


recherche_post:
   path:     /posts/chercherpost/
   defaults: { _controller: EspritApiBundle:Blog:findpost }

list_blog:
   path:     /posts/listblog
   defaults: { _controller: EspritApiBundle:Blog:listBlogClientMob }


   
create_post:
    path:     /posts/create
    defaults: { _controller: EspritApiBundle:Blog:new }    

delete_post:
    path:     /posts/delete/{id}
    defaults: { _controller: EspritApiBundle:Blog:delete }

    
update_post:
    path:     /posts/update/{id}
    defaults: { _controller: EspritApiBundle:Blog:update }


detailed_post:
    path:     /detailedpost1/{id}
    defaults: { _controller: EspritApiBundle:Blog:showdetailed }







commentsall:
    path:     /comments/all
    defaults: { _controller: EspritApiBundle:Blog:commentsall }


add_comment:
    path:     /addcomment/{user}/{id}/{Con}
    defaults: { _controller: EspritApiBundle:Blog:addComment }

update_comment:
    path:     /updatecomment/{id}/{coment}
    defaults: { _controller: EspritApiBundle:Blog:updatetcomment }

delete_comment:
    path:     /deletecomment/{id}
    defaults: { _controller: EspritApiBundle:Blog:deletecomment }




comment_like:
    path: /like/{id}
    defaults: { _controller: EspritApiBundle:Blog:like }




alluser:
    path:     /users/all
    defaults: { _controller: EspritApiBundle:Blog:alluser }

delete_user:
    path:     /users/delete/{id}
    defaults: { _controller: EspritApiBundle:Blog:deleteuser }
    
login1:
    path:     /login1/{username}/{password}
    defaults: { _controller: AppBundle:Default:login }

registe1:
    path:     /registe1/{email}/{username}/{password}/{role}
    defaults: { _controller: AppBundle:Default:register }

allcommentaire:
    path:     /commentaires/all
    defaults: { _controller: EspritApiBundle:Blog:allcommentaire }