<?php

namespace EventBundle\Repository;

/**
 * whyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class whyRepository extends \Doctrine\ORM\EntityRepository
{
}
