<?php

namespace RentBundle\Repository;

/**
 * EventEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
