<?php

namespace RentBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryRepository extends \Doctrine\ORM\EntityRepository
{
}
