velo_annonce_homepage:
    path:     /
    defaults: { _controller: VeloAnnonceBundle:Default:index }
velo_list_annonce:
    path:     /annonce/list
    defaults: { _controller: VeloAnnonceBundle:Annonce:list }
velo_afficher_annonce:
    path:     /annonce/list/{id}
    defaults: { _controller: VeloAnnonceBundle:Annonce:annonce }
velo_ajouter_annonce:
    path:     /annonce/add
    defaults: { _controller: VeloAnnonceBundle:Annonce:add }
velo_modifier_annonce:
    path:     /annonce/edit/{id}
    defaults: { _controller: VeloAnnonceBundle:Annonce:edit }
velo_supprimer_annonce:
    path:     /annonce/delete/{id}
    defaults: { _controller: VeloAnnonceBundle:Annonce:delete }
velo_signaler_annonce:
    path:     /annonce/signal/{id}/{cause}
    defaults: { _controller: VeloAnnonceBundle:Annonce:signal }
velo_my_annonce:
    path:     /annonce/mesannonces
    defaults: { _controller: VeloAnnonceBundle:Annonce:myList }
velo_recherche_categorie_annonce:
    path:     /annonce/categorie/{categorie}
    defaults: { _controller: VeloAnnonceBundle:Annonce:rechercheCategorie }
velo_recherche_type_velo_annonce:
    path:     /annonce/typevelo/{typeVelo}
    defaults: { _controller: VeloAnnonceBundle:Annonce:rechercheTypeVelo }
velo_tri_prix_velo_annonce:
    path:     /annonce/triprix/{choix}
    defaults: { _controller: VeloAnnonceBundle:Annonce:triPrix }
velo_tri_date_velo_annonce:
    path:     /annonce/tridate
    defaults: { _controller: VeloAnnonceBundle:Annonce:triDate }
velo_recherche_annonce:
    path:     /annonce/recherche/{recherche}
    defaults: { _controller: VeloAnnonceBundle:Annonce:recherche }
velo_recherche_type_annonce:
    path:     /annonce/recherche/type/{type}
    defaults: { _controller: VeloAnnonceBundle:Annonce:rechercheType }
velo_admin_annonce:
    path:     /admin
    defaults: { _controller: VeloAnnonceBundle:AdminAnnonce:index }
velo_admin_list_annonce:
    path:     /admin/annonce/list
    defaults: { _controller: VeloAnnonceBundle:AdminAnnonce:listAnnonce }
velo_admin_affiche_annonce:
    path:     /admin/annonce/list/{id}
    defaults: { _controller: VeloAnnonceBundle:AdminAnnonce:afficheAnnonce }
velo_admin_add_annonce:
    path:     /admin/annonce/add
    defaults: { _controller: VeloAnnonceBundle:AdminAnnonce:addAnnonce }
velo_admin_edit_annonce:
    path:     /admin/annonce/edit/{id}
    defaults: { _controller: VeloAnnonceBundle:AdminAnnonce:editAnnonce }
velo_admin_delete_annonce:
    path:     /admin/annonce/delete/{id}
    defaults: { _controller: VeloAnnonceBundle:AdminAnnonce:deleteAnnonce }
velo_admin_signaled_annonce:
    path:     /admin/annonce/signaledlist/
    defaults: { _controller: VeloAnnonceBundle:AdminAnnonce:listAnnonceSignalee }
velo_admin_stat_annonce:
    path:     /admin/stat
    defaults: { _controller: VeloAnnonceBundle:AdminAnnonce:statAnnonce }

velo_admin_profile_user:
    path:     /admin/user/{id}
    defaults: { _controller: VeloAnnonceBundle:AdminAnnonce:profile }
#velo_list_mobile_annonce:
#    path:     /annonce/listm
#    defaults: { _controller: VeloAnnonceBundle:AnnonceMobile:afficherAnnonces }
#velo_ma_list_mobile_annonce:
#    path:     /annonce/mesannoncem/
#    defaults: { _controller: VeloAnnonceBundle:AnnonceMobile:afficherMesAnnonces }
#velo_recherche_list_mobile_annonce:
#    path:     /annonce/recherche/
#    defaults: { _controller: VeloAnnonceBundle:AnnonceMobile:rechercheAnnonces }
#velo_ajouter_mobile_annonce:
#    path:     /annonce/ajoutm/
#    defaults: { _controller: VeloAnnonceBundle:AnnonceMobile:ajouterAnnonces }
#velo_supprimer_mobile_annonce:
#    path:     /annonce/supprimerm/
#    defaults: { _controller: VeloAnnonceBundle:AnnonceMobile:supprimerAnnonce }
#velo_modifier_mobile_annonce:
#    path:     /annonce/modifierm/
#    defaults: { _controller: VeloAnnonceBundle:AnnonceMobile:modifierAnnonce }
#velo_stat_gouv_mobile_annonce:
#    path:     /annonce/statgm
#    defaults: { _controller: VeloAnnonceBundle:AnnonceMobile:statGouvAnnonces }
#velo_mobile_signal_annonce:
#    path:     /annonce/reportm/
#    defaults: { _controller: VeloAnnonceBundle:AnnonceMobile:signalm }
#velo_stat_sign_cat_mobile_annonce:
#    path:     /annonce/statsc
#    defaults: { _controller: VeloAnnonceBundle:AnnonceMobile:statSignalCatAnnonces }
#velo_stat_sign_cau_mobile_annonce:
#    path:     /annonce/statscau
#    defaults: { _controller: VeloAnnonceBundle:AnnonceMobile:statSignalCauseAnnonces }
#velo_stat_type_mobile_annonce:
#    path:     /annonce/statty
#    defaults: { _controller: VeloAnnonceBundle:AnnonceMobile:statTypeAnnonces }
#velo_list_signal_mobile_annonce:
#    path:     /annonce/listsignm
#    defaults: { _controller: VeloAnnonceBundle:AnnonceMobile:afficherAnnoncesSign }
#velo_list_cat_mobile_annonce:
#    path:     /annonce/listcat/
#    defaults: { _controller: VeloAnnonceBundle:AnnonceMobile:afficherAnnoncesCat }
#velo_list_prix_mobile_annonce:
#    path:     /annonce/listprix/
#    defaults: { _controller: VeloAnnonceBundle:AnnonceMobile:afficherAnnoncesPrix }
#velo_list_date_mobile_annonce:
#    path:     /annonce/listdate
#    defaults: { _controller: VeloAnnonceBundle:AnnonceMobile:afficherAnnoncesDate }
#velo_cause_mobile_annonce:
#    path:     /annonce/cause/
#    defaults: { _controller: VeloAnnonceBundle:AnnonceMobile:causesAnnonce }