<?php

namespace CircuitsBundle\Repository;

/**
 * CircuitsCommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CircuitsCommentsRepository extends \Doctrine\ORM\EntityRepository
{
}
